import React from "react"
import Layout from "../components/layout"
import SEO from "../components/seo"
import { Link } from "gatsby"


const PrivacyPage = (props) => {

  return (
    <Layout>
      <SEO title="Privacy policy" />

      <div className="container">

        <section className="mt-6">

          <h1 className="text-primary">Privacy policy</h1>
          
          <p className="text-justify mt-4">
            This is the Privacy Policy for the website hosted at <a href="https://birminghamurbanobservatory.com" className="text-link text-link:hover">https://birminghamurbanobservatory.com</a> and web applications hosted on subdomains such <a href="https://data.birminghamurbanobservatory.com" className="text-link text-link:hover">https://data.birminghamurbanobservatory.com</a>. They are operated by, or on behalf of, researchers at the <a href="https://www.birmingham.ac.uk/" className="text-link text-link:hover">University of Birmingham</a>. We are committed to protecting and respecting your privacy.
          </p>

          <p className="text-justify mt-4">
            The University has its own <a href="https://www.birmingham.ac.uk/university/governance/policies-regs/data-protection.aspx" className="text-link text-link:hover">data protection policies</a> which also apply.
          </p>

        </section>

        <section className="mt-8">
          <h1 className="text-primary">Information we collect about you</h1>

          <h2 className="text-primary font-bold">Users of our websites and APIs</h2>
          <p className="text-justify mt-2">This applies to all users of our services when they visit our websites, or consume data from our APIs.</p>

          <ul className="list-disc">
            <li className="mt-2">We obtain your IP address when you visit our website. This is required for us to communicate with your browser and for rate-limiting. Your browser usually also provides information describing its ‘user agent’, and the site which referred you (if applicable). You can configure your browser to obscure this information without affecting our services. This data is stored within our log files for up to one month to allow us to identify faults in our systems and fix them.</li>
            <li className="mt-2">We may store ‘cookies’ on your computer to allow our website to operate correctly. If you wish to avoid storage of cookies from our websites, then please configure your browser to reject these.</li>
          </ul>

          <h2 className="text-primary font-bold">Users who Log In</h2>
          <p className="text-justify mt-2">Some of the web applications we operate require the user to log in with an email and password or a social sign-in  (e.g. Google Account). In order to operate this login service additional information is collected:</p>

          <ul className="list-disc">
            <li className="mt-2">Authentication in our web applications and API is performed using <a href="https://jwt.io">JSON Web Tokens</a> which are generated by a third-party service from <a href="https://auth0.com/" className="text-link text-link:hover">Auth0</a>. Auth0 are responsible for storing the user credentials required to login. For example, your email and encrypted password are stored in Auth0's system rather than within a Birmingham Urban Observatory database. This is because Auth0 have far greater experience storing such information securely.</li>
            <li className="mt-2">Users opting to login with a Google Account will provide the following information from their account: <em>Basic Profile</em> information (email and verified email flag) and <em>Extended Profile</em> information (name, public profile URL, photo, country, language and timezone). We may use this information to personalise your experience in our web application, e.g. showing your name and photo alongside your account information.</li>
            <li className="mt-2">Neither us, or Auth0, will use your email address for marketing, and will not do so in future unless you explicitly provide consent. In exceptional circumstances, we may email you if we identify problems with data you have previously requested. If you chose to opt-in to certain services, e.g. receiving alerts about sensors, then we may send alert emails to the email address you used to login.</li>
          </ul>

        </section>

        <section className="mt-8">
          <h1 className="text-primary font-bold">Your rights</h1>
          <p className="mt-2 text-justify">
            Please see the details on this <a href="https://www.birmingham.ac.uk/university/governance/policies-regs/data-protection.aspx" className="text-link text-link:hover">page</a> for more information about your legal rights. Please use our <Link to="/contact" className="text-link text-link:hover">Contact Us Form</Link> for further queries or requests to access, rectify, or remove data, and any other right under the Data Protection Act 2018.
          </p>
        </section>

      </div>

      <br/>

    </Layout>
  )

}

export default PrivacyPage;



